{% set name = "loos" %}
{% set version = "4.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GrossfieldLab/loos/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3994d212a7204a970ae0fcb9d49176a8a7623ed1c58b7d21e2b044cc5409e600

build:
  skip: true  # [win]
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - swig
  host:
    - python
    - pip
    - numpy
    - boost-cpp
    - openblas
    - libnetcdf
    - liblapack
    - eigen
    
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - scikit-learn
    - boost-cpp

test:
  requires:
    - pip
  imports:
    - loos
    - loos.pyloos
    - loos.pyloos.trajectories
    - loos.OptimalMembraneGenerator
    - loos.Voronoi
  commands:
    - pip check
    - loos_version

about:
  home: https://github.com/GrossfieldLab/loos
  summary: 'The Lightweight Object Oriented Structure analysis Library'
  description: |
    LOOS is a C++ library for developing new tools to analyze molecular
    dynamics simulations. It is designed to provide good performance while
    greatly simplifying the process of creating new methods, particularly when
    using its python interface. This package contains roughly 100 useful tools,
    as well as the python bindings needed to create new tools. If you wish to 
    write a new C++ tool or modify the library itself, we recommend you instead 
    clone LOOS from GitHub.
  license: GPL-3.0-only
  license_family: GPL3
  license_file: COPYING
  doc_url: https://grossfieldlab.github.io/loos
  dev_url: https://github.com/GrossfieldLab/loos

extra:
  recipe-maintainers:
    - agrossfield
    - tromo
