{% set name = "loos" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  url: https://github.com/GrossfieldLab/loos/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ee617cebb8a3a7041fcdf2e5a6ab53359677c5aedde35d6c188bee3e9a08f173

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - swig
    - python >=3.9
  host:
    - python >=3.9
    - pip
    - numpy
    - libboost
    - libboost-devel
    - libboost-headers
    - openblas
    - libnetcdf
    - liblapack
    - eigen
    - gemmi
    - zlib
    - setuptools
    
  run:
    - python >=3.9
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('libboost') }}
    - {{ pin_compatible('libboost-devel') }}
    - scipy
    - scikit-learn
    - gemmi

test:
  requires:
    - pip
  imports:
    - loos
    - loos.pyloos
    - loos.pyloos.trajectories
    - loos.OptimalMembraneGenerator
    - loos.Voronoi
  commands:
    - pip check
    - loos_version

about:
  home: https://github.com/GrossfieldLab/loos
  summary: 'The Lightweight Object Oriented Structure analysis Library'
  description: |
    LOOS is a C++ library for developing new tools to analyze molecular
    dynamics simulations. It is designed to provide good performance while
    greatly simplifying the process of creating new methods, particularly when
    using its python interface. This package contains roughly 100 useful tools,
    as well as the python bindings needed to create new tools. If you wish to 
    write a new C++ tool or modify the library itself, we recommend you instead 
    clone LOOS from GitHub.
  license: GPL-3.0-only
  license_family: GPL3
  license_file: COPYING
  doc_url: https://grossfieldlab.github.io/loos
  dev_url: https://github.com/GrossfieldLab/loos

extra:
  recipe-maintainers:
    - agrossfield
    - tromo
